name: Deploy via FTP

on:
  push:
    branches:
      - master  # ou a branch que você quiser monitorar

jobs:
  ftp-deploy:
    name: Deploy to Hostinger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v@v4.3.x
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/wp-content/themes/illumina  # Ajuste conforme seu caminho no Hostinger
